default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL_TEST'] %>

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
 cache:                              # <--- ADD THIS
    <<: *default                      # <--- ADD THIS
    url: <%= ENV['DATABASE_URL'] %>   # <--- ADD THIS
